add new features
Anankke/SSPanel-Uim pull request #1364
Opened 2021-11-16 17:34 UTC by iamsaltedfish

- 添加按时间范围返利功能
- 用户编辑页面及相关控制器代码优化
- 依照 https://github.com/Anankke/SSPanel-Uim/issues/1359 提议，现在可在后台用户资料编辑页面修改用户昵称

2021-11-16 19:35 UTC, Anankke requested changes
坏改，描述原来写的挺明白的，改完反而丢失信息

2021-11-16 19:53 UTC, M1Screw commented
名稱的修改是沒有問題的，就是可以參考節點新建和編輯頁面用備注的方式加一行配置説明。

2021-11-16 19:58 UTC, M1Screw commented
還有一個想法，就是可以把配置説明加到輸入欄的 html 的 title tag裏面，這樣鼠標懸浮在輸入框上時就會顯示輸入提示。

2021-11-16 19:58 UTC, M1Screw commented
參考這個 commit https://github.com/Anankke/SSPanel-Uim/commit/3a343d3751f2fb5c9109c9f1492b010c72a4165f

2021-11-16 22:49 UTC, iamsaltedfish commented
> 還有一個想法，就是可以把配置説明加到輸入欄的 title tag裏面，這樣鼠標懸浮在輸入框上時就會顯示輸入提示。

手机也有这个效果么

2021-11-16 22:51 UTC, iamsaltedfish commented
按错了。。。

2021-11-16 22:53 UTC, iamsaltedfish commented
> 坏改，描述原来写的挺明白的，改完反而丢失信息

没明白，具体有哪些项目

2021-11-18 23:02 UTC, ecyecy commented
大佬，账户信息登录记录后边能加个登录时间吗

2021-11-24 17:01 UTC, closed without merging